
###Signup
POST /api/signup HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "hainh",
  "email": "nguyenhoangha12i@gmail.com",
  "password": "abc@123"
}


###Login
POST localhost:3000/api/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "email":"nguyenhoanghai@gmail.com",
  "password" :"abc@123"
}

###Logout
POST http://localhost:3000/api/logout HTTP/1.1
Host: localhost:3000
x-client-id: 21
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxLCJlbWFpbCI6Im5ndXllbmhvYW5naGFpQGdtYWlsLmNvbSIsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTcyOTY5MDk5NywiZXhwIjoxNzI5ODYzNzk3fQ.e9rZi-lIqxJTvXG0-9_jAVbiyg5-g_5NUJM41K1ptL0


###Refresh Token

POST localhost:3000/api/handler-refresh-token HTTP/1.1
Host: localhost:3000
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2LCJlbWFpbCI6Im5ndXllbmhvYW5naGFpQGdtYWlsLmNvbSIsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTczMDIxMTg3NywiZXhwIjoxNzMwODE2Njc3fQ.7TA3m5omU9a-C3fv1gusMH2TZzRRAF79rR0keEwHvyQ
x-client-id: 26
Content-Type: application/json


###GetProducts
GET  http://localhost:3000/api/products-hehe?minPrice=10&maxPrice=100 HTTP/1.1
Host: localhost:3000
Content-Type: application/json



###GetCategorys
GET  http://localhost:3000/api/categorys HTTP/1.1
Host: localhost:3000
Content-Type: application/json

